const WORDS = [
  ['planet','Space','A large world that travels around a star.'],['bridge','Structures','A construction that carries a route across a gap.'],['kettle','Kitchen','A vessel used to boil water.'],['shadow','Light','A dark shape made when light is blocked.'],['pocket','Clothing','A small sewn compartment for carrying things.'],
  ['garden','Outdoors','Ground cultivated for flowers, fruit or vegetables.'],['whisper','Sound','Speech made very quietly.'],['compass','Navigation','An instrument that indicates direction.'],['thunder','Weather','The sound that follows a flash of lightning.'],['blanket','Home','A warm covering used on a bed.'],
  ['puzzle','Games','A problem designed to test ingenuity.'],['anchor','Sailing','A heavy object that holds a vessel in place.'],['window','Buildings','A glazed opening that admits light.'],['camera','Objects','A device used to record images.'],['forest','Nature','A large area covered chiefly with trees.'],
  ['silver','Materials','A pale precious metal and chemical element.'],['rabbit','Animals','A small mammal with long ears.'],['button','Clothing','A small fastener, or a control you press.'],['castle','Buildings','A large fortified residence.'],['magnet','Science','An object that attracts iron.'],
  ['bubble','Objects','A thin sphere enclosing air or gas.'],['ladder','Tools','A set of rungs used for climbing.'],['orange','Food','A citrus fruit that is also a colour.'],['pencil','Stationery','A graphite writing and drawing tool.'],['island','Geography','Land completely surrounded by water.'],
  ['helmet','Protection','A hard covering worn on the head.'],['candle','Home','Wax surrounding a wick that gives light.'],['rocket','Space','A vehicle propelled for travel beyond Earth.'],['basket','Containers','A woven container used for carrying things.'],['mirror','Home','A surface that reflects an image.']
].map(([word,category,definition])=>({word,category,definition}));

const storage={today:'glyphToday',history:'glyphHistory',intro:'glyphIntroSeen'};
const localDateFor=date=>{const p=v=>String(v).padStart(2,'0');return `${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}`};
const dateKey=localDateFor(new Date());
function seedFromString(value){let seed=2166136261;for(const char of value){seed^=char.charCodeAt(0);seed=Math.imul(seed,16777619)}return seed>>>0}
function randomGenerator(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let value=Math.imul(seed^seed>>>15,1|seed);value=value+Math.imul(value^value>>>7,61|value)^value;return((value^value>>>14)>>>0)/4294967296}}
const random=randomGenerator(seedFromString(`glyph-${dateKey}`));
function shuffle(items){const copy=[...items];for(let index=copy.length-1;index>0;index-=1){const target=Math.floor(random()*(index+1));[copy[index],copy[target]]=[copy[target],copy[index]]}return copy}
const dailyWords=shuffle(WORDS).slice(0,5);

const els={puzzle:document.querySelector('#puzzle-stage'),reveal:document.querySelector('#reveal-stage'),skyline:document.querySelector('#target-skyline'),form:document.querySelector('#guess-form'),input:document.querySelector('#guess-input'),history:document.querySelector('#guess-history'),hint:document.querySelector('#hint-button'),next:document.querySelector('#next-button'),status:document.querySelector('#game-status'),help:document.querySelector('#help-dialog'),stats:document.querySelector('#stats-dialog'),result:document.querySelector('#result-dialog'),toast:document.querySelector('#snackbar')};
let round=0,attempt=1,hintLevel=0,hintPenalty=0,results=[],completedResult=null;
const ascenders=new Set('bdfhklt'),descenders=new Set('gjpqy'),narrow=new Set('fijlt'),wide=new Set('mw'),rounded=new Set('acdegopqsu');
function profile(letter){return{height:ascenders.has(letter)?'ascender':descenders.has(letter)?'descender':'body',width:narrow.has(letter)?'narrow':wide.has(letter)?'wide':'normal',rounded:rounded.has(letter)}}
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function glyphMarkup(word,{vowels=false,revealIndex=-1}={}){return [...word].map((letter,index)=>{const shape=profile(letter);const classes=['glyph-cell',shape.height,shape.width,shape.rounded?'rounded':'',vowels&&'aeiou'.includes(letter)?'is-vowel':''].filter(Boolean).join(' ');return `<span class="${classes}" aria-hidden="true"><i class="glyph-stroke"></i>${index===revealIndex?`<b class="revealed-letter">${letter}</b>`:''}</span>`}).join('')}
function renderSkyline(){const item=dailyWords[round];const revealIndex=hintLevel>=3?Math.floor(item.word.length/2):-1;els.skyline.innerHTML=glyphMarkup(item.word,{vowels:hintLevel>=1,revealIndex});document.querySelector('#category-label').textContent=item.category;document.querySelector('#letter-count').textContent=`${item.word.length} letters`;document.querySelector('#round-value').textContent=`${round+1} / 5`;document.querySelector('#attempt-value').textContent=String(4-attempt);document.querySelector('#score-value').textContent=String(results.reduce((sum,item)=>sum+item.points,0));els.input.maxLength=item.word.length;els.input.placeholder=`${item.word.length}-letter word`}
function prepareRound(){attempt=1;hintLevel=0;hintPenalty=0;els.puzzle.hidden=false;els.reveal.hidden=true;els.history.replaceChildren();els.input.value='';els.input.disabled=false;els.hint.disabled=false;document.querySelector('#hint-copy').textContent='No extra clue revealed';els.hint.innerHTML='Mark vowel positions <span>-40</span>';renderSkyline();els.status.textContent=`Word ${round+1} is ready.`;els.input.focus({preventScroll:true})}
function shapeMatches(guess,answer){return [...guess].reduce((count,letter,index)=>{if(!answer[index])return count;const left=profile(letter),right=profile(answer[index]);return count+(left.height===right.height&&left.width===right.width&&left.rounded===right.rounded?1:0)},0)}
function addGuess(guess){const answer=dailyWords[round].word;const matches=shapeMatches(guess,answer);const row=document.createElement('div');row.className='guess-row';row.innerHTML=`<code>${guess}</code><div class="profile-track" aria-label="${matches} of ${answer.length} glyph profiles match">${[...answer].map((_,index)=>`<i class="${index<guess.length&&JSON.stringify(profile(guess[index]))===JSON.stringify(profile(answer[index]))?'match':''}"></i>`).join('')}</div><span>${matches}/${answer.length} profiles match</span>`;els.history.prepend(row)}
function submitGuess(event){event.preventDefault();const item=dailyWords[round];const guess=els.input.value.trim().toLowerCase().replace(/[^a-z]/g,'');if(guess.length!==item.word.length){els.status.textContent=`Enter exactly ${item.word.length} letters.`;return}if(guess===item.word){const points=Math.max(0,300-(attempt-1)*75-hintPenalty);revealWord(points,true);return}addGuess(guess);if(attempt>=3){revealWord(0,false);return}attempt+=1;els.input.value='';renderSkyline();els.status.textContent=`Not that word. ${4-attempt} ${4-attempt===1?'attempt':'attempts'} remaining.`;els.input.focus()}
function useHint(){const item=dailyWords[round];hintLevel+=1;if(hintLevel===1){hintPenalty+=40;document.querySelector('#hint-copy').textContent='Vowel positions are marked below the silhouette.';els.hint.innerHTML='Reveal definition <span>-60</span>'}else if(hintLevel===2){hintPenalty+=60;document.querySelector('#hint-copy').textContent=item.definition;els.hint.innerHTML='Reveal one letter <span>-80</span>'}else{hintPenalty+=80;document.querySelector('#hint-copy').textContent=`${item.definition} One letter is now visible.`;els.hint.disabled=true;els.hint.textContent='All clues revealed'}renderSkyline();els.status.textContent=`Clue revealed. Maximum remaining value: ${Math.max(0,300-(attempt-1)*75-hintPenalty)} points.`}
function revealWord(points,solved){const item=dailyWords[round];results.push({points,solved,noHint:solved&&hintLevel===0});els.puzzle.hidden=true;els.reveal.hidden=false;document.querySelector('#reveal-word').textContent=item.word;document.querySelector('#reveal-definition').textContent=item.definition;document.querySelector('#round-score').textContent=`+${points}`;els.next.innerHTML=round===4?'See today\'s result':'Next silhouette <span aria-hidden="true">&rarr;</span>';els.status.textContent=solved?`${item.word}: solved for ${points} points.`:`The word was ${item.word}.`}
function nextRound(){if(round===4){finishGame();return}round+=1;prepareRound()}
function resultFromRounds(){return{date:dateKey,score:results.reduce((sum,item)=>sum+item.points,0),solved:results.filter(item=>item.solved).length,noHint:results.filter(item=>item.noHint).length,rounds:results.map(item=>item.points)}}
function renderResult(result,open=true){document.querySelector('#result-mark').textContent=result.score;document.querySelector('#result-title').textContent=result.solved===5?'Every skyline read.':result.solved>=3?'The shapes are becoming words.':'A difficult set of silhouettes.';document.querySelector('#result-summary').textContent=`You identified ${result.solved} of 5 words for ${result.score} points.`;document.querySelector('#final-score').textContent=result.score;document.querySelector('#words-solved').textContent=`${result.solved} / 5`;document.querySelector('#no-hint-count').textContent=result.noHint;document.querySelector('#round-pips').innerHTML=result.rounds.map((points,index)=>`<span title="Word ${index+1}">${points}</span>`).join('');if(open&&!els.result.open)els.result.showModal()}
function finishGame(){const result=resultFromRounds();completedResult=result;localStorage.setItem(storage.today,JSON.stringify(result));const history=readJson(storage.history,[]).filter(item=>item.date!==dateKey);history.push({date:dateKey,score:result.score});localStorage.setItem(storage.history,JSON.stringify(history.slice(-100)));renderStats();renderResult(result);els.puzzle.hidden=false;els.reveal.hidden=true;els.puzzle.innerHTML=`<div class="complete-state"><span class="eyebrow">Daily complete</span><h2>Today's five glyphs are read.</h2><p>You scored ${result.score} points. A new typographic set arrives tomorrow.</p><button class="primary-button" id="view-result" type="button">View today's result</button></div>`;document.querySelector('#view-result').addEventListener('click',()=>renderResult(result));els.status.textContent='Daily challenge complete. Come back tomorrow.'}
function showCompleted(result){completedResult=result;els.puzzle.innerHTML=`<div class="complete-state"><span class="eyebrow">Daily complete</span><h2>Today's five glyphs are read.</h2><p>You scored ${result.score} points. A new typographic set arrives tomorrow.</p><button class="primary-button" id="view-result" type="button">View today's result</button></div>`;els.reveal.hidden=true;document.querySelector('#view-result').addEventListener('click',()=>renderResult(result));document.querySelector('#round-value').textContent='5 / 5';document.querySelector('#attempt-value').textContent='--';document.querySelector('#score-value').textContent=result.score;els.status.textContent='Daily challenge complete. Come back tomorrow.'}
function streakFor(history){const dates=new Set(history.map(item=>item.date));const cursor=new Date(`${dateKey}T12:00:00`);if(!dates.has(dateKey))cursor.setDate(cursor.getDate()-1);let streak=0;while(dates.has(localDateFor(cursor))){streak+=1;cursor.setDate(cursor.getDate()-1)}return streak}
function renderStats(){const history=readJson(storage.history,[]);document.querySelector('#games-played').textContent=history.length;document.querySelector('#record-average').textContent=history.length?Math.round(history.reduce((sum,item)=>sum+item.score,0)/history.length):'--';document.querySelector('#record-best').textContent=history.length?Math.max(...history.map(item=>item.score)):'--';document.querySelector('#current-streak').textContent=streakFor(history)}
function toast(message){els.toast.textContent=message;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2200)}
async function share(){const result=completedResult||readJson(storage.today,null);if(!result)return;const text=`Glyph ${result.score}/1500\n${result.rounds.map(value=>value?`▰ ${value}`:'▱ 0').join('\n')}\n${result.solved}/5 silhouettes read`;try{if(navigator.share)await navigator.share({title:'Glyph',text,url:location.href});else await navigator.clipboard.writeText(`${text}\n${location.href}`);toast(navigator.share?'Share sheet opened':'Result copied')}catch(error){if(error.name!=='AbortError')toast('Could not share this result')}}
els.form.addEventListener('submit',submitGuess);els.hint.addEventListener('click',useHint);els.next.addEventListener('click',nextRound);document.querySelector('#help-button').addEventListener('click',()=>els.help.showModal());document.querySelector('#stats-button').addEventListener('click',()=>{renderStats();els.stats.showModal()});document.querySelector('#share-button').addEventListener('click',share);document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
const saved=readJson(storage.today,null);renderStats();if(saved?.date===dateKey)showCompleted(saved);else{prepareRound();if(!localStorage.getItem(storage.intro)){els.help.showModal();localStorage.setItem(storage.intro,'true')}}
