const MODES={trail:{label:'Trail',size:6,scans:5},explorer:{label:'Explorer',size:8,scans:5},expert:{label:'Expert',size:10,scans:4}};
const STORAGE_KEY='xy:v2';
const elements={setup:document.querySelector('#setup-panel'),play:document.querySelector('#play-panel'),grid:document.querySelector('#grid'),mode:document.querySelector('#mode-label'),scans:document.querySelector('#scan-label'),arrow:document.querySelector('#clue-arrow'),kicker:document.querySelector('#clue-kicker'),title:document.querySelector('#clue-title'),copy:document.querySelector('#clue-copy'),help:document.querySelector('#help-dialog'),result:document.querySelector('#result-dialog')};
const loadStats=()=>{try{return{played:0,wins:0,streak:0,best:0,...JSON.parse(localStorage.getItem(STORAGE_KEY))}}catch{return{played:0,wins:0,streak:0,best:0}}};
const stats=loadStats();
let selectedMode='trail';
let game=null;

function start(mode=selectedMode){selectedMode=mode;const config=MODES[mode];game={...config,treasure:randomCell(config.size),scansLeft:config.scans,clues:[],visited:new Set(),status:'playing'};elements.setup.hidden=true;elements.play.hidden=false;elements.mode.textContent=`${config.label.toUpperCase()} MAP`;setClue('◎','MAKE YOUR FIRST SCAN','Pick any coordinate','We’ll tell you which way—and how far—the treasure lies.');render();}
function randomCell(size){return{x:Math.floor(Math.random()*size),y:Math.floor(Math.random()*size)}}
function key(x,y){return`${x},${y}`}
function render(){elements.scans.textContent=`${game.scansLeft} ${game.scansLeft===1?'scan':'scans'} left`;elements.grid.style.setProperty('--size',game.size);elements.grid.replaceChildren();const possible=possibleCells();for(let y=0;y<game.size;y++)for(let x=0;x<game.size;x++){const button=document.createElement('button');button.type='button';button.className='cell';button.dataset.x=x;button.dataset.y=y;button.setAttribute('role','gridcell');button.setAttribute('aria-label',`X ${x+1}, Y ${y+1}`);button.textContent=`${x+1},${y+1}`;const id=key(x,y);if(game.status!=='playing')button.disabled=true;if(game.visited.has(id))button.classList.add('scanned');else if(game.clues.length&&possible.has(id))button.classList.add('possible');else if(game.clues.length)button.classList.add('cleared');if(game.status!=='playing'&&x===game.treasure.x&&y===game.treasure.y){button.className='cell treasure';button.textContent='×';button.setAttribute('aria-label',`Treasure at X ${x+1}, Y ${y+1}`)}elements.grid.append(button)}}
function possibleCells(){const cells=new Set();for(let y=0;y<game.size;y++)for(let x=0;x<game.size;x++){if(game.visited.has(key(x,y)))continue;const fits=game.clues.every(clue=>Math.abs(x-clue.x)+Math.abs(y-clue.y)===clue.distance&&Math.sign(x-clue.x)===clue.dx&&Math.sign(y-clue.y)===clue.dy);if(fits)cells.add(key(x,y))}return cells}
function scan(x,y){if(!game||game.status!=='playing'||game.visited.has(key(x,y)))return;if(x===game.treasure.x&&y===game.treasure.y)return finish(true);const previous=game.clues.at(-1)?.distance;const dx=Math.sign(game.treasure.x-x),dy=Math.sign(game.treasure.y-y),distance=Math.abs(game.treasure.x-x)+Math.abs(game.treasure.y-y);game.clues.push({x,y,dx,dy,distance});game.visited.add(key(x,y));game.scansLeft--;const direction=directionName(dx,dy);const trend=previous===undefined?'':distance<previous?' · Warmer':distance>previous?' · Colder':' · Same distance';const candidates=possibleCells().size;setClue(directionArrow(dx,dy),`${direction.toUpperCase()} · ${distance} GRID ${distance===1?'STEP':'STEPS'}`,`${candidates} possible ${candidates===1?'spot':'spots'} remain${candidates===1?'s':''}`,`The treasure is ${direction.toLowerCase()} from your scan${trend}. Follow the glowing search area.`);if(game.scansLeft===0)finish(false);else render()}
function directionName(dx,dy){const vertical=dy<0?'North':dy>0?'South':'';const horizontal=dx<0?'West':dx>0?'East':'';return vertical&&horizontal?`${vertical}-${horizontal}`:vertical||horizontal}
function directionArrow(dx,dy){return{'0,-1':'↑','1,-1':'↗','1,0':'→','1,1':'↘','0,1':'↓','-1,1':'↙','-1,0':'←','-1,-1':'↖'}[`${dx},${dy}`]}
function setClue(arrow,kicker,title,copy){elements.arrow.textContent=arrow;elements.kicker.textContent=kicker;elements.title.textContent=title;elements.copy.textContent=copy}
function finish(won){game.status=won?'won':'lost';stats.played++;if(won){stats.wins++;stats.streak++;stats.best=Math.max(stats.best,stats.streak)}else stats.streak=0;localStorage.setItem(STORAGE_KEY,JSON.stringify(stats));updateStats();render();document.querySelector('#result-icon').textContent=won?'×':'·';document.querySelector('#result-icon').style.background=won?'var(--sand)':'var(--danger)';document.querySelector('#result-kicker').textContent=won?'TREASURE FOUND':'MAP REVEALED';document.querySelector('#result-title').textContent=won?'You found the X.':'The trail went cold.';document.querySelector('#result-copy').textContent=won?`Found at X ${game.treasure.x+1}, Y ${game.treasure.y+1} with ${game.scansLeft} scans left.`:`The treasure was at X ${game.treasure.x+1}, Y ${game.treasure.y+1}.`;setTimeout(()=>elements.result.showModal(),450)}
function updateStats(){document.querySelector('#streak-value').textContent=stats.streak;document.querySelector('#best-value').textContent=stats.best;document.querySelector('#winrate-value').textContent=stats.played?`${Math.round(stats.wins/stats.played*100)}%`:'—'}
function showSetup(){elements.result.close();elements.play.hidden=true;elements.setup.hidden=false}
document.querySelectorAll('[data-difficulty]').forEach(button=>button.addEventListener('click',()=>start(button.dataset.difficulty)));
elements.grid.addEventListener('click',event=>{const cell=event.target.closest('.cell');if(cell)scan(Number(cell.dataset.x),Number(cell.dataset.y))});
document.querySelector('#help-button').addEventListener('click',()=>elements.help.showModal());document.querySelectorAll('.dialog-close,[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
document.querySelector('#new-button').addEventListener('click',()=>start());document.querySelector('#back-button').addEventListener('click',showSetup);document.querySelector('#again-button').addEventListener('click',()=>{elements.result.close();start()});document.querySelector('#change-button').addEventListener('click',showSetup);
updateStats();if(!localStorage.getItem('xy:welcomed')){localStorage.setItem('xy:welcomed','1');elements.help.showModal()}
