import { axisDifferenceCopy, clueSummary, coordinateClue } from './clues.js';

const MODES={trail:{label:'Trail',size:6,scans:5},explorer:{label:'Explorer',size:8,scans:5},expert:{label:'Expert',size:10,scans:4}};
const STORAGE_KEY='xy:v2';
const elements={setup:document.querySelector('#setup-panel'),play:document.querySelector('#play-panel'),grid:document.querySelector('#grid'),mode:document.querySelector('#mode-label'),scans:document.querySelector('#scan-label'),arrow:document.querySelector('#clue-arrow'),kicker:document.querySelector('#clue-kicker'),title:document.querySelector('#clue-title'),copy:document.querySelector('#clue-copy'),help:document.querySelector('#help-dialog'),result:document.querySelector('#result-dialog')};
const loadStats=()=>{try{return{played:0,wins:0,streak:0,best:0,...JSON.parse(localStorage.getItem(STORAGE_KEY))}}catch{return{played:0,wins:0,streak:0,best:0}}};
const stats=loadStats();
let selectedMode='trail';
let game=null;

function start(mode=selectedMode){selectedMode=mode;const config=MODES[mode];game={...config,treasure:randomCell(config.size),scansLeft:config.scans,clues:[],visited:new Set(),status:'playing'};elements.setup.hidden=true;elements.play.hidden=false;elements.mode.textContent=`${config.label.toUpperCase()} MAP`;setClue('◎','MAKE YOUR FIRST SCAN','Pick any coordinate','We’ll give you the direction, total steps and X/Y distance difference.');render();}
function randomCell(size){return{x:Math.floor(Math.random()*size),y:Math.floor(Math.random()*size)}}
function key(x,y){return`${x},${y}`}
function render(){elements.scans.textContent=`${game.scansLeft} ${game.scansLeft===1?'scan':'scans'} left`;elements.grid.style.setProperty('--size',game.size);elements.grid.replaceChildren();for(let y=0;y<game.size;y++)for(let x=0;x<game.size;x++){const button=document.createElement('button');button.type='button';button.className='cell';button.dataset.x=x;button.dataset.y=y;button.setAttribute('role','gridcell');button.setAttribute('aria-label',`X ${x+1}, Y ${y+1}`);button.textContent=`${x+1},${y+1}`;const id=key(x,y);if(game.status!=='playing')button.disabled=true;if(game.visited.has(id))button.classList.add('scanned');if(game.status!=='playing'&&x===game.treasure.x&&y===game.treasure.y){button.className='cell treasure';button.textContent='×';button.setAttribute('aria-label',`Treasure at X ${x+1}, Y ${y+1}`)}elements.grid.append(button)}}
function scan(x,y){if(!game||game.status!=='playing'||game.visited.has(key(x,y)))return;if(x===game.treasure.x&&y===game.treasure.y)return finish(true);const previous=game.clues.at(-1)?.distance;const clue=coordinateClue(x,y,game.treasure.x,game.treasure.y);const {xDirection:dx,yDirection:dy,totalDistance:distance,axisDifference}=clue;game.clues.push({x,y,dx,dy,distance,axisDifference});game.visited.add(key(x,y));game.scansLeft--;const direction=directionName(dx,dy);const trend=previous===undefined?'':distance<previous?' · Warmer':distance>previous?' · Colder':' · Same distance';setClue(directionArrow(dx,dy),clueSummary(direction.toUpperCase(),distance,axisDifference),`Scan logged at X ${x+1}, Y ${y+1}`,`${axisDifferenceCopy(axisDifference)} The treasure is ${direction.toLowerCase()} from your scan${trend}. Combine this with your earlier clues.`);if(game.scansLeft===0)finish(false);else render()}
function directionName(dx,dy){const vertical=dy<0?'North':dy>0?'South':'';const horizontal=dx<0?'West':dx>0?'East':'';return vertical&&horizontal?`${vertical}-${horizontal}`:vertical||horizontal}
function directionArrow(dx,dy){return{'0,-1':'↑','1,-1':'↗','1,0':'→','1,1':'↘','0,1':'↓','-1,1':'↙','-1,0':'←','-1,-1':'↖'}[`${dx},${dy}`]}
function setClue(arrow,kicker,title,copy){elements.arrow.textContent=arrow;elements.kicker.textContent=kicker;elements.title.textContent=title;elements.copy.textContent=copy}
function finish(won){game.status=won?'won':'lost';stats.played++;if(won){stats.wins++;stats.streak++;stats.best=Math.max(stats.best,stats.streak)}else stats.streak=0;localStorage.setItem(STORAGE_KEY,JSON.stringify(stats));updateStats();render();document.querySelector('#result-icon').textContent=won?'×':'·';document.querySelector('#result-icon').style.background=won?'var(--sand)':'var(--danger)';document.querySelector('#result-kicker').textContent=won?'TREASURE FOUND':'MAP REVEALED';document.querySelector('#result-title').textContent=won?'You found the X.':'The trail went cold.';document.querySelector('#result-copy').textContent=won?`Found at X ${game.treasure.x+1}, Y ${game.treasure.y+1} with ${game.scansLeft} scans left.`:`The treasure was at X ${game.treasure.x+1}, Y ${game.treasure.y+1}.`;setTimeout(()=>elements.result.showModal(),450)}
function updateStats(){document.querySelector('#streak-value').textContent=stats.streak;document.querySelector('#best-value').textContent=stats.best;document.querySelector('#winrate-value').textContent=stats.played?`${Math.round(stats.wins/stats.played*100)}%`:'—'}
function showSetup(){elements.result.close();elements.play.hidden=true;elements.setup.hidden=false}
document.querySelectorAll('[data-difficulty]').forEach(button=>button.addEventListener('click',()=>start(button.dataset.difficulty)));
elements.grid.addEventListener('click',event=>{const cell=event.target.closest('.cell');if(cell)scan(Number(cell.dataset.x),Number(cell.dataset.y))});
document.querySelector('#help-button').addEventListener('click',()=>elements.help.showModal());document.querySelectorAll('.dialog-close,[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
document.querySelector('#new-button').addEventListener('click',()=>start());document.querySelector('#back-button').addEventListener('click',showSetup);document.querySelector('#again-button').addEventListener('click',()=>{elements.result.close();start()});document.querySelector('#change-button').addEventListener('click',showSetup);
const tutorial={stage:0,grid:document.querySelector('#tutorial-grid'),copy:document.querySelector('#tutorial-copy'),clue:document.querySelector('#tutorial-clue'),done:document.querySelector('#tutorial-done'),dialog:document.querySelector('#tutorial-dialog')};
function renderTutorial(){const next=[key(0,3),key(1,0),key(3,1)][tutorial.stage];const possible=tutorial.stage===1?new Set([key(2,0),key(3,1)]):tutorial.stage===2?new Set([key(3,1)]):new Set();tutorial.grid.replaceChildren();for(let y=0;y<4;y++)for(let x=0;x<4;x++){const button=document.createElement('button');button.type='button';button.dataset.x=x;button.dataset.y=y;button.textContent=`${x+1},${y+1}`;button.setAttribute('aria-label',`Training coordinate X ${x+1}, Y ${y+1}`);const id=key(x,y);if(possible.has(id))button.classList.add('demo-possible');if((tutorial.stage>0&&id===key(0,3))||(tutorial.stage>1&&id===key(1,0)))button.className='demo-scanned';if(id===next)button.classList.add('next');if(tutorial.stage===3&&id===key(3,1)){button.className='demo-treasure';button.textContent='×'}tutorial.grid.append(button)}}
function advanceTutorial(x,y){const expected=[[0,3],[1,0],[3,1]][tutorial.stage];if(!expected||x!==expected[0]||y!==expected[1])return;tutorial.stage++;if(tutorial.stage===1){tutorial.copy.innerHTML='The X is <strong>north-east, 5 steps in total</strong>, and its horizontal and vertical distances <strong>differ by 1</strong>. The two glowing cells both fit. Now scan <strong>X 2, Y 1</strong>.';tutorial.clue.textContent='↗ North-east · 5 steps total · X/Y difference 1';}else if(tutorial.stage===2){tutorial.copy.innerHTML='This clue is <strong>south-east, 3 steps total, X/Y difference 1</strong>. Only one square fits both scans. Tap <strong>X 4, Y 2</strong>.';tutorial.clue.textContent='↘ South-east · 3 steps total · X/Y difference 1';}else{tutorial.copy.innerHTML='<strong>Training complete.</strong> In a real hunt, you will make these deductions yourself—no possible answers will glow.';tutorial.clue.textContent='× Treasure found at X 4, Y 2';tutorial.done.hidden=false;}renderTutorial()}
tutorial.grid.addEventListener('click',event=>{const button=event.target.closest('button');if(button)advanceTutorial(Number(button.dataset.x),Number(button.dataset.y))});
tutorial.done.addEventListener('click',()=>{localStorage.setItem('xy:tutorialComplete','1');localStorage.setItem('xy:welcomed','1');tutorial.dialog.close()});
updateStats();if(!localStorage.getItem('xy:tutorialComplete')){renderTutorial();tutorial.dialog.showModal()}else if(!localStorage.getItem('xy:welcomed')){localStorage.setItem('xy:welcomed','1');elements.help.showModal()}
