const BANK={
  A:[['CAT','A domestic feline',1],['MAP','A guide to places',1],['HAND','The end part of an arm',1],['PLANT','A living thing with roots',2],['GLASS','A transparent drinking material',2],['TRACK','A marked course or trail',2],['STAMP','A small mark for sending post',2],['CRANE','A tall lifting machine or bird',2]],
  E:[['PEN','A writing tool',1],['BED','A place to sleep',1],['SHELL','A hard outer covering',2],['DESK','Furniture used for work',1],['CHEST','A large box or upper torso',2],['FENCE','A boundary made of posts',1],['BLEND','Mix smoothly together',2],['STEP','One movement of the foot',2]],
  I:[['FISH','An animal that swims with gills',1],['RING','A circular band',1],['SHIP','A large seagoing vessel',2],['MILK','A pale drink from mammals',1],['BRICK','A rectangular building block',2],['CLIMB','Move upwards',2],['STICK','A thin piece of wood',2],['DRINK','Take liquid into the mouth',2]],
  O:[['DOG','A loyal canine',1],['FORK','A utensil with prongs',1],['GLOVE','A covering for the hand',2],['STONE','A small piece of rock',2],['CLOCK','A device that tells time',2],['SHORE','Land beside water',2],['CROWN','A royal headpiece',2],['FROST','A thin layer of ice crystals',2]],
  U:[['SUN','Our nearest star',1],['CUP','A small drinking vessel',1],['DRUM','A percussion instrument',2],['BRUSH','A tool with bristles',2],['CLOUD','A visible mass in the sky',3],['TRUCK','A road vehicle for goods',2],['PLUMB','Exactly vertical',2],['FLUTE','A slender wind instrument',2]]
};
const storage={today:'borrowedLettersToday',history:'borrowedLettersHistory',intro:'borrowedLettersIntroSeen'};
const localDateFor=date=>{const p=v=>String(v).padStart(2,'0');return `${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}`};const dateKey=localDateFor(new Date());
function seedFromString(value){let seed=2166136261;for(const char of value){seed^=char.charCodeAt(0);seed=Math.imul(seed,16777619)}return seed>>>0}
function randomGenerator(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let value=Math.imul(seed^seed>>>15,1|seed);value=value+Math.imul(value^value>>>7,61|value)^value;return((value^value>>>14)>>>0)/4294967296}}
const random=randomGenerator(seedFromString(`borrowed-${dateKey}`));
function shuffle(items){const copy=[...items];for(let index=copy.length-1;index>0;index-=1){const target=Math.floor(random()*(index+1));[copy[index],copy[target]]=[copy[target],copy[index]]}return copy}
const puzzle=shuffle(Object.entries(BANK).map(([letter,items])=>{const [word,clue,index]=items[Math.floor(random()*items.length)];return{word,clue,index,letter}}));
const corrupt=puzzle.map((entry,index)=>{const next=puzzle[(index+1)%puzzle.length].letter;return entry.word.slice(0,entry.index)+next+entry.word.slice(entry.index+1)});
const els={ring:document.querySelector('#letter-ring'),pass:document.querySelector('#pass-button'),hint:document.querySelector('#hint-button'),feedback:document.querySelector('#feedback-panel'),status:document.querySelector('#game-status'),help:document.querySelector('#help-dialog'),stats:document.querySelector('#stats-dialog'),result:document.querySelector('#result-dialog'),toast:document.querySelector('#snackbar')};
let selections=Array(5).fill(null),locked=new Set(),attempt=1,hints=0,lastResults=Array(5).fill(null),completedResult=null;
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function potentialScore(){return Math.max(0,1000-(attempt-1)*200-hints*100)}
function render(){els.ring.innerHTML=puzzle.map((entry,nodeIndex)=>`<article class="word-node ${lastResults[nodeIndex]===true?'is-repaired':lastResults[nodeIndex]===false?'is-broken':''} ${locked.has(nodeIndex)?'is-hinted':''}" data-node="${nodeIndex}"><span class="node-number">Word ${nodeIndex+1}</span><p class="node-clue">${entry.clue}</p><div class="letter-buttons" role="group" aria-label="Select the borrowed letter in ${corrupt[nodeIndex]}">${[...corrupt[nodeIndex]].map((letter,letterIndex)=>`<button class="letter-button" type="button" data-letter="${letterIndex}" aria-pressed="${selections[nodeIndex]===letterIndex}" ${locked.has(nodeIndex)?'disabled':''}>${letter}</button>`).join('')}</div><div class="result-word">${typeof lastResults[nodeIndex]==='boolean'?(lastResults[nodeIndex]?entry.word:'Not repaired'):''}</div></article>`).join('');document.querySelector('#attempt-value').textContent=`${attempt} / 4`;document.querySelector('#repaired-value').textContent=`${lastResults.filter(Boolean).length} / 5`;document.querySelector('#score-value').textContent=potentialScore().toLocaleString();els.hint.disabled=locked.size===5;els.pass.disabled=selections.some(value=>value===null);els.ring.querySelectorAll('.letter-button').forEach(button=>button.addEventListener('click',selectLetter))}
function selectLetter(event){const node=Number(event.currentTarget.closest('.word-node').dataset.node);if(locked.has(node))return;selections[node]=Number(event.currentTarget.dataset.letter);lastResults=Array(5).fill(null);els.feedback.hidden=true;render();els.status.textContent=selections.every(value=>value!==null)?'All five intruders selected. Ready to pass.':`Select ${selections.filter(value=>value===null).length} more ${selections.filter(value=>value===null).length===1?'letter':'letters'}.`}
function simulate(){const selected=selections.map((position,index)=>corrupt[index][position]);return puzzle.map((entry,index)=>{const incoming=selected[(index-1+5)%5];const position=selections[index];return corrupt[index].slice(0,position)+incoming+corrupt[index].slice(position+1)})}
function passLetters(){if(selections.some(value=>value===null))return;const words=simulate();lastResults=words.map((word,index)=>word===puzzle[index].word);render();if(lastResults.every(Boolean)){finish(true);return}const repaired=lastResults.filter(Boolean).length;els.feedback.hidden=false;els.feedback.innerHTML=`<strong>${repaired} of 5 words repaired.</strong> The pass returned ${words.map(word=>`<code>${word}</code>`).join(', ')}. Keep useful selections and rethink the rest.`;if(attempt>=4){finish(false);return}attempt+=1;document.querySelector('#attempt-value').textContent=`${attempt} / 4`;document.querySelector('#score-value').textContent=potentialScore().toLocaleString();els.status.textContent=`${repaired} repaired. Adjust the circuit for pass ${attempt}.`}
function useHint(){const candidates=puzzle.map((_,index)=>index).filter(index=>!locked.has(index)&&selections[index]!==puzzle[index].index);const fallback=puzzle.map((_,index)=>index).filter(index=>!locked.has(index));const target=(candidates.length?candidates:fallback)[0];if(target===undefined)return;selections[target]=puzzle[target].index;locked.add(target);hints+=1;lastResults=Array(5).fill(null);els.feedback.hidden=false;els.feedback.innerHTML=`Word ${target+1}'s borrowed letter has been selected and locked.`;render();els.status.textContent=`One intruder revealed. ${potentialScore()} points remain available.`}
function resultData(solved){return{date:dateKey,score:solved?potentialScore():0,solved,passes:attempt,hints,answers:puzzle.map(item=>item.word)}}
function renderResult(result,open=true){document.querySelector('#result-mark').textContent=result.score;document.querySelector('#result-title').textContent=result.solved?'Every letter is home.':'The circuit stayed tangled.';document.querySelector('#result-summary').textContent=result.solved?`All five words repaired in ${result.passes} ${result.passes===1?'pass':'passes'}.`:'The answers have been revealed. A new circuit arrives tomorrow.';document.querySelector('#final-score').textContent=result.score;document.querySelector('#passes-used').textContent=result.passes;document.querySelector('#hints-used').textContent=result.hints;document.querySelector('#answer-list').innerHTML=result.answers.map(word=>`<span>${word}</span>`).join('');if(open&&!els.result.open)els.result.showModal()}
function finish(solved){const result=resultData(solved);completedResult=result;localStorage.setItem(storage.today,JSON.stringify(result));const history=readJson(storage.history,[]).filter(item=>item.date!==dateKey);history.push({date:dateKey,score:result.score});localStorage.setItem(storage.history,JSON.stringify(history.slice(-100)));renderStats();renderResult(result);showComplete(result)}
function showComplete(result){document.querySelector('.borrow-card').innerHTML=`<div class="run-strip"><div><span>Passes</span><strong>${result.passes}</strong></div><div><span>Hints</span><strong>${result.hints}</strong></div><div><span>Score</span><strong>${result.score}</strong></div></div><div class="complete-state"><span class="eyebrow">Daily complete</span><h2>${result.solved?'Circuit repaired.':'Circuit revealed.'}</h2><p>${result.answers.join(' · ')}</p><button class="primary-button" id="view-result" type="button">View today's result</button></div>`;document.querySelector('#view-result').addEventListener('click',()=>renderResult(result))}
function streakFor(history){const dates=new Set(history.map(item=>item.date));const cursor=new Date(`${dateKey}T12:00:00`);if(!dates.has(dateKey))cursor.setDate(cursor.getDate()-1);let streak=0;while(dates.has(localDateFor(cursor))){streak+=1;cursor.setDate(cursor.getDate()-1)}return streak}
function renderStats(){const history=readJson(storage.history,[]);document.querySelector('#games-played').textContent=history.length;document.querySelector('#record-average').textContent=history.length?Math.round(history.reduce((sum,item)=>sum+item.score,0)/history.length):'--';document.querySelector('#record-best').textContent=history.length?Math.max(...history.map(item=>item.score)):'--';document.querySelector('#current-streak').textContent=streakFor(history)}
function toast(message){els.toast.textContent=message;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2200)}
async function share(){const result=completedResult||readJson(storage.today,null);if(!result)return;const text=`Borrowed Letters ${result.score}/1000\n${result.solved?'● ● ● ● ●':'○ ○ ○ ○ ○'}\n${result.passes} ${result.passes===1?'pass':'passes'} · ${result.hints} ${result.hints===1?'hint':'hints'}`;try{if(navigator.share)await navigator.share({title:'Borrowed Letters',text,url:location.href});else await navigator.clipboard.writeText(`${text}\n${location.href}`);toast(navigator.share?'Share sheet opened':'Result copied')}catch(error){if(error.name!=='AbortError')toast('Could not share this result')}}
els.pass.addEventListener('click',passLetters);els.hint.addEventListener('click',useHint);document.querySelector('#help-button').addEventListener('click',()=>els.help.showModal());document.querySelector('#stats-button').addEventListener('click',()=>{renderStats();els.stats.showModal()});document.querySelector('#share-button').addEventListener('click',share);document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
const saved=readJson(storage.today,null);renderStats();if(saved?.date===dateKey){completedResult=saved;showComplete(saved)}else{render();if(!localStorage.getItem(storage.intro)){els.help.showModal();localStorage.setItem(storage.intro,'true')}}
